# DB
spring:
  profiles:
    include: local
  datasource:
    # local-mysql-db-test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(D511Ue3hdf749uMSnR4KnxghKJdREasdHnjS85SqCtBQKaqfg5xua8HlbIuFt1WMyt1o9Y8my0tQDwWM5CUvDNQurmR8OVq6FYS7poqwR0klY7Zh9N5fUvhlvaxE95CJjDvOI/RXUK4g8ZyV/YG1oBJp3dbXD7oGsu0M+DlSm1zKJzOQZMd11fVpKTpLitUjSH/zQ0ZzhSdomqcs1JCA9A==)
    username: ENC(LwaUlCU/lPuLy/Gj3O6nyO2JXELuy/cUrmqOUZjl0kkgGWslUwEO5AU7XJL2osuA)
    password: ENC(SSVWhmhOaFjLLf32zoIgMUDBNtJH6r8iFPdzatpR8pvPRe0ucI4fs4D6Tu4SawGB)
  # JPA
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# Logging level
logging:
  level:
    com:
      duktown: debug

#jasypt
jasypt:
  encryptor:
    bean: jasyptEncryptorAES