# DB
spring:
  datasource:
    # local-mysql-db-test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/duktown?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: duktown
    password: 1234
  # local-h2-db-test
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/duktown
#    username: sa
#    password:
  # JPA
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create

# Logging level
logging:
  level:
    com:
      duktown: debug

# JWT
custom:
  jwt:
    secret-key:
      custom_jwt_secret_key_for_local_test_secret_key_secret_secret_key