# DB
spring:
  profiles:
    include: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${duktown.datasource.url}
    username: ${duktown.datasource.username}
    password: ${duktown.datasource.password}
  # JPA
  jpa:
    hibernate:
      ddl-auto: ${jpa-hibernate-ddl-auto}
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  # mail
  mail:
    host: ${duktown.mail.host}
    port: ${duktown.mail.port}
    username: ${duktown.mail.username}
    password: ${duktown.mail.password}
    properties:
      mail:
        smtp:
          auth: ${duktown.mail.properties.mail.smtp.auth}
          starttls:
            enable: ${duktown.mail.properties.mail.smtp.starttls.enable}
            required: ${duktown.mail.properties.mail.smtp.starttls.required}
          connection_timeout: ${duktown.mail.properties.mail.smtp.connection_timeout}
          timeout: ${duktown.mail.properties.mail.smtp.timeout}
          write_timeout: ${duktown.mail.properties.mail.smtp.write_timeout}
    auth-code-expiration-millis: ${duktown.mail.auth-code-expiration-millis}

# Logging level
logging:
  level:
    com:
      duktown: ${duktown.logging.level.com.duktown}

#jasypt
jasypt:
  encryptor:
    bean: jasyptEncryptorAES

# CUSTOM
custom:
  # JWT
  jwt:
    secret-key:
      ${duktown.custom.jwt.secret-key}
  # CORS
  cors:
    originUrl:
      ${duktown.custom.cors.originUrl}
  # SEED
  seed:
    pbsz:
      user:
        key: ${duktown.custom.seed.pbsz.user.key}
      iv: ${duktown.custom.seed.pbsz.iv}
  demo:
    pwd: ${duktown.custom.demo.pwd}
  jasypt:
    key: ${duktown.custom.jasypt.key}
    algorithm: ${duktown.custom.jasypt.algorithm}