# DB
spring:
  profiles:
    include: local
  datasource:
    # local-mysql-db-test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(JVueZoKtXw4kIZwcep06zxINLMkSAlqfMGDvab76y51kJsqpuOWFqEYM/VLpYFrZEvPi95XaSO8w+/wyK3D7256xZJWsnXlzqBavCkaQ9ET74Pv1D1hKugeJOmPgticFJtHhrOFtIqB2FeYKT5Ptk28tc1DnfZ14kaoWxpA/NH/HIro4IaA9ldiFakEVlJjhxajVTPmt81fmLh6zKSDYSickg2hYHZdk8tTFKSrOHFlW3IlZZ3wOkLZwlenD8RkmczVu62y/GI96wAAn5hByzg/QjoZ4DsV65I8Hd4x3b9w=)
    username: ENC(oHZcnMbXKHW+hkey8ZJce+7N6F3wYmRfiuc0t+bEUYYWR6Dcvgd7zVG+gB0qz9Zm)
    password: ENC(E8sbVtAaWmW3V6JI8RGGvZW3qArudjsLRK7NzHijB9G3rfk9AQ/oZYLnkmeldxwwyWG1BzR2JNv2C4DiSuhxog==)
  # JPA
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# Logging level
logging:
  level:
    com:
      duktown: debug

#jasypt
jasypt:
  encryptor:
    bean: jasyptEncryptorAES